POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7,
    "user": "5ca73e651de4755d54467e09"
  }